language: go

go:
    - "1.7.1"

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Deepesh Nathani"
        - GIT_EMAIL="ndeep_27@yahoo.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

before_install:
- openssl aes-256-cbc -K $encrypted_89fc506dcdf7_key -iv $encrypted_89fc506dcdf7_iv -in travis_key.enc -out ~\/.ssh/travis_key -d

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

after_success:
    - echo "ndeepesh.github.io" > ./public/CNAME
    - ./scripts/deploy.sh
