language: go
go:
- 1.7.1
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Deepesh Nathani"
  - GIT_EMAIL="ndeep_27@yahoo.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
after_success:
- echo "ndeepesh.github.io" > ./public/CNAME
- ./scripts/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_89fc506dcdf7_key -iv $encrypted_89fc506dcdf7_iv
  -in travis_key.enc -out travis_key -d
script:
- git clone https://github.com/alexurquhart/hugo-geo ./themes/hugo-geo
- hugo
install:
- go get -v github.com/spf13/hugo
